apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-user-api
  name: udagram-user-api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-user-api