version: "3"
services:
 reverseproxy:
   image: kojof/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: kojof/udagram-user-api
  volumes:
   #- C:\Users\kojof\.aws
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRES_USERNAME: $POSTGRES_USERNAME
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
   POSTGRES_DB: $POSTGRES_DB 
   POSTGRES_HOST: $POSTGRES_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://18.132.126.50:8100"
 backend-feed:
  image: kojof/udagram-feed-api
  volumes:
   #- C:\Users\kojof\.aws
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRES_USERNAME: $POSTGRES_USERNAME
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
   POSTGRES_DB: $POSTGRES_DB 
   POSTGRES_HOST: $POSTGRES_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://18.132.126.50:8100"
 frontend:
  image: kojof/udagram-frontend
  ports:
   - "8100:80"