version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: kojof/reverseproxy 
  backend_user:
    build:
      context: ../../udagram-user-api
    image: kojof/udagram-user-api
  backend_feed:
    build:
      context: ../../udagram-feed-api  
    image: kojof/udagram-feed-api 
  frontend:
    build:
      context: ../../udagram-frontend 
    image: kojof/udagram-frontend:local